# Damper Automations
- id: '1676525972977'
  alias: Open All Zones
  description: ''
  trigger: []
  condition: []
  action:
  - type: turn_off
    device_id: 492ad6551d06b00d22a156bdde30507f
    entity_id: switch.power_strip_5_damper_1
    domain: switch
  - type: turn_off
    device_id: 492ad6551d06b00d22a156bdde30507f
    entity_id: switch.power_strip_6_damper_2
    domain: switch
  mode: single
- id: '1677732984708'
  alias: Close Zone 1
  description: ''
  trigger: []
  condition: []
  action:
  - type: turn_off
    device_id: 492ad6551d06b00d22a156bdde30507f
    entity_id: switch.power_strip_6_damper_2
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - type: turn_on
    device_id: 492ad6551d06b00d22a156bdde30507f
    entity_id: switch.power_strip_5_damper_1
    domain: switch
  mode: single
- id: '1677733147879'
  alias: Close Zone 2
  description: ''
  trigger: []
  condition: []
  action:
  - type: turn_off
    device_id: 492ad6551d06b00d22a156bdde30507f
    entity_id: switch.power_strip_5_damper_1
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - type: turn_on
    device_id: 492ad6551d06b00d22a156bdde30507f
    entity_id: switch.power_strip_6_damper_2
    domain: switch
  mode: single
- id: '1677733183899'
  alias: Open Zone 1
  description: ''
  trigger: []
  condition: []
  action:
  - type: turn_off
    device_id: 492ad6551d06b00d22a156bdde30507f
    entity_id: switch.power_strip_5_damper_1
    domain: switch
  mode: single
- id: '1677733202266'
  alias: Open Zone 2
  description: ''
  trigger: []
  condition: []
  action:
  - type: turn_off
    device_id: 492ad6551d06b00d22a156bdde30507f
    entity_id: switch.power_strip_6_damper_2
    domain: switch
  mode: single

# Nice looking lock buttons in dashboard
- id: '1678386842095'
  alias: "Lock: status"
  description: ""
  trigger:
    - platform: time_pattern
      seconds: 10
      id: time
    - platform: event
      event_type: google_assistant_sdk_custom_event
      event_data:
        request: Is my front door locked
      id: status
  condition: []
  action:
    - choose:
      - conditions:
          - condition: trigger
            id: time
        sequence:
          - service: google_assistant_sdk.send_text_command
            data:
              command: Is my front door locked
      - conditions:
          - condition: trigger
            id: status
        sequence:
          - service: input_text.set_value
            data:
              value: "{{ trigger.event.data.response }}"
            target:
              entity_id: input_text.lock_status
  mode: queued
  max: 10
