# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
# Include all script files from the 'scripts/' directory
script: !include_dir_list scripts/
script default: !include scripts.yaml
scene: !include scenes.yaml

# HTTPS configuration
http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_k

google_assistant: !include google_assistant_integration.yaml

# Allow Scenes/Scripts/Automations to show up in Google
switch:
  - platform: template
    switches:
      script_my_thing:
        turn_on:
          service: script.my_thing
        turn_off:
          service: script.my_thing # something different here?
        value_template: '{{is_state("script.my_thing", "on")}}'
