# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
# Include all script files from the 'scripts/' directory
script: !include_dir_list scripts/
script default: !include scripts.yaml
scene: !include scenes.yaml

http:
  # ssl_certificate: fullchain2.pem
  # ssl_key: privkey2.pem
  # ssl_certificate: certs/fullchain.pem
  # ssl_key: certs/privkey.pem
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_k

google_assistant: !include google_assistant_integration.yaml
