# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
# Include all script files from the 'scripts/' directory
script: !include_dir_list scripts/
script default: !include scripts.yaml
scene: !include scenes.yaml

# HTTPS configuration
http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_k

google_assistant: !include google_assistant_integration.yaml

# Allow Scenes/Scripts/Automations to show up in Google
#   ToDo: make this an !include file(?)
switch:
  - platform: template
    switches:
      # Allow 'my_thing' script
      script_my_thing:
        turn_on:
          service: script.my_thing
        turn_off:
          service: script.my_thing # something different here?
        # Check if this is necessary
        value_template: '{{is_state("script.my_thing", "on")}}'
      # Allow 'spring' scene
      scene_make_lights_spring:
        turn_on:
          service: scene.turn_on
          entity_id: scene.make_lights_spring
        turn_off:
          service: scene.turn_off # video has this as on?
          entity_id: scene.make_lights_spring
      # Allow 'lights off' scene
      scene_all_lights_off:
        turn_on:
          service: scene.turn_on
          entity_id: scene.all_lights_off
        turn_off:
          service: scene.turn_off # video has this as on?
          entity_id: scene.all_lights_off
      # Allow 'lights flash at 9am' automation
      automation_flash_lights_at_9am:
        turn_on:
          service: automation.turn_on
          entity_id: automation.flash_lights_at_9am
        turn_off:
          service: automation.turn_ff
          entity_id: automation.flash_lights_at_9am
        # Check if this is necessary
        value_template: '{{is_state("automation.flash_lights_at_9am", "on")}}'
