# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
# Include all script files from the 'scripts/' directory
script: !include_dir_list scripts/
script default: !include scripts.yaml
scene: !include scenes.yaml

# Shows how to reference a secret credential
# Stored in 'secrets.yaml' by convention, but other filenames
#   work too, as shown here.
#auth_providers:
#  - type: legacy_api_password
#    api_password: !secret my_secret_credential
