
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include_dir_list scripts/ # include everything in this directory
script default: !include scripts.yaml # include a single file
scene: !include scenes.yaml
