# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# Example: https://github.com/Burnett01/rsync-deployments
# another example: https://stackoverflow.com/questions/67516571/github-action-triggered-by-success-of-a-different-action

name: Deploy to EC2

on:
  workflow_run: # Only run this if linting and testing pass
    workflows: ["Lint"] # is this the correct workflow name? also add lintint back later
    types: [completed] # don't know if this will work

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "First workflow was a failure"

